### ISSUE TITLE
2. Positioning

### ISSUE THREAD

**Issue by emrb9** [NvmKassem/e-academy#12]
**2.1.	Problem Statement**
Provide a statement summarizing the problem being solved by this project. 
The following format may be used
The problem of: [describe the problem] 
Affects: [the stakeholders affected by the problem] 
The impact of which is: [what is the impact of the problem?] 
A successful solution would be: [list some key benefits of a successful solution]

**2.2.	Product Position Statement**
Provide an overall statement summarizing, at the highest level, the unique position the product intends to fill in the marketplace. A product position statement communicates the application's intent and the project's importance to all concerned personnel. 
The following format may be used
For: [target customer] 
Who: [statement of the need or opportunity] 
The [Project Name]: is a [product category] 
That: [statement of key benefit; that is, the compelling reason to buy] 
Unlike: [primary competitive alternative] 
Our product: [statement of primary differentiation]

**Comment by beezzyy** [comment]
The positioning part has been added to the final document. Please review before closing

**Comment by yoniabitbol** [comment]
Reviewed. Closing.
