### ISSUE TITLE
3. Stakeholder Descriptions

### ISSUE THREAD

**Issue by emrb9** [NvmKassem/e-academy#13]
**3.1.	Stakeholder Summary** 
There are a number of stakeholders with an interest in the development and not all of them are end users. Present a summary list of these non-user stakeholders. (The users are summarized in section 3.2.)
The following format may be used
Name: [Name the stakeholder type.]
Description: [Briefly describe the stakeholder.]
Responsibilities: [Summarize the stakeholder’s key responsibilities with regard to the system being developed; that is, their interest as a stakeholder.]

**3.2.	User Summary** 
Present a summary list of all identified users.
The following format may be used
Name: [Name the stakeholder type.]
Description: [Briefly describe what they represent with respect to the system.]
Responsibilities: [List the user's key responsibilities with regard to the system being developed.]	
Stakeholder: [If the user is not directly represented, identify which stakeholder is responsible for representing the user's interests.]

**Comment by yoniabitbol** [comment]
Added stakeholder description as well as user summary. Please review :)

**Comment by beezzyy** [comment]
Great! This part has been reviewed!
