### ISSUE TITLE
4. Product Overview

### ISSUE THREAD

**Issue by emrb9** [NvmKassem/e-academy#14]
**4.1.	Product Perspective** 
This subsection of the Vision document puts the product in perspective to other related products and the user’s environment. 
If the product is independent and totally self-contained, state it here. 
If the product is a component of a larger system, then this subsection needs to relate how these systems interact and needs to identify the relevant interfaces between the systems. 
One easy way to display the major components of the larger system, interconnections, and external interfaces is with a block diagram.

**Comment by AymanMansoor** [comment]
Task Complete and Updated. Requirements have been written and the feature list filled.
