### ISSUE TITLE
5. Product Features

### ISSUE THREAD

**Issue by emrb9** [NvmKassem/e-academy#15]
**5.1.	Core Features** 
List and briefly describe the product features. 
Features are the high-level capabilities of the system that are necessary to deliver benefits to the users. Each feature is an externally desired service that typically requires a series of inputs to achieve the desired result. Throughout this section, each feature will be externally perceivable by users, operators, or other external systems. 
These features should include a description of functionality and any relevant usability issues that must be addressed. 
The following guidelines apply:
Avoid design. Keep feature descriptions at a general level. Focus on capabilities needed and why (not how) they should be implemented.

**5.2.	Other Product Requirements**
At a high level, list applicable standards, hardware, or platform requirements; performance requirements; and environmental requirements. 
Define the quality ranges for performance, robustness, fault tolerance, usability, and similar characteristics that are not captured in the Feature Set. 
Note any design constraints, external constraints, or other dependencies. 
Define any specific documentation requirements, including user manuals, online help, installation, labeling, and packaging requirements. 
Define the priority of these other product requirements. Include, if useful, attributes such as stability, benefit, effort, and risk.

**Comment by anisdzdev** [comment]
Task Complete and Updated. Requirements have been written and the feature list filled.
