### ISSUE TITLE
6. Risk and Feasibility

### ISSUE THREAD

**Issue by emrb9** [NvmKassem/e-academy#16]
Risk assessment and proposed mitigation techniques

**6.1.	Feasibility:** 
Technical feasibility and all related issues (time, context, technology…).
Organizational feasibility such as who will be part of the work in terms of responsible, stakeholders.
Financial feasibility 
**6.2.	Risk:** 
At least 3 risks from each category: domain-specific risks and process-related risks.

**Comment by NvmKassem** [comment]
Finished Feasibility, still need to complete the risks section

**Comment by NvmKassem** [comment]
Finished the risk assessments
