### ISSUE TITLE
Generate Group Report

### ISSUE THREAD

**Issue by beezzyy** [NvmKassem/e-academy#33]
Add a section for the GUI snapshot and add a section for quality assurance and change management following the vision document

Subtasks:
#29 
#30 
#34

**Comment by beezzyy** [comment]
The report has been generated. Just missing the snapshots and the quality assurance & change management!

**Comment by emrb9** [comment]
#29 completed by youssef
#30 completed by jonathan h
#34 completed by emilie 
Submitted 
task is completed
