### ISSUE TITLE
Phase I Report

### ISSUE THREAD

**Issue by beezzyy** [NvmKassem/e-academy#4]
GOOGLE DOCS: https://docs.google.com/document/d/14sfIckzeTm5H5aCR6bEUwGuyZkiBB2H1NEGqArxRK9k/edit

The first step will be brainstorming ideas and exploring the available products on the market. You need 
to do a comparative study of the different available systems with their features. At least three systems 
should be found and compared to your system.

The second part of your initiation phase is your product presentation. You need to explain what it offers
and how it is different from the existing products. You need to look up the different requirements 
elicitation techniques and write a document summarizing your findings (two elicitation techniques are 
needed). The core features your product offers are: 
• Accounts for the different users.
• A request system (receiving and attribution

![image](https://user-images.githubusercontent.com/91300383/192156232-37c77e4d-cb8e-4a38-a338-0911d40bf18c.png)

**Comment by beezzyy** [comment]
The report has been finalized!

**Comment by yoniabitbol** [comment]
All subtasks have been finalized and closed.
