### ISSUE TITLE
Find 3 Similar Systems and Study their Features

### ISSUE THREAD

**Issue by beezzyy** [NvmKassem/e-academy#6]
Task: #4 

The first step will be brainstorming ideas and exploring the available products on the market. You need 
to do a comparative study of the different available systems with their features. At least three systems 
should be found and compared to your system.

**Comment by beezzyy** [comment]
Adir -  Khan Academy
Reuven - Succes Scolaire
Jonathan Abitbol - SuperProf

**Comment by yoniabitbol** [comment]
Completed SuperProf and added to the google docs

**Comment by beezzyy** [comment]
Khan Academy has been completed and has been added to the google docs
