### ISSUE TITLE
Part II: E-Academy presentation

### ISSUE THREAD

**Issue by beezzyy** [NvmKassem/e-academy#8]
Task: #4 

![image](https://user-images.githubusercontent.com/91300383/192012689-42046dee-5246-4a65-a038-85d9c1e5d9ef.png)

**Comment by NvmKassem** [comment]
Anis did the Features section and I did the Users and the Values sections. This task was completed.

**Comment by NvmKassem** [comment]
Missing the paragraph where we compare our platform to the other ones.

**Comment by NvmKassem** [comment]
Completed the comparison paragraph.
